services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
            - ./storage/app/public:/var/www/storage/app/public
        ports:
            - "${NGINX_PORT}:80"
        environment:
            - NGINX_PORT=${NGINX_PORT}
        depends_on:
            - app
        container_name: nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
            - ./_docker/app/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./_docker/app/${OPCACHE_FILE:-opcache.ini}:/usr/local/etc/php/conf.d/opcache.ini
            - ./_docker/supervisord.conf:/etc/supervisord.conf
        depends_on:
            - db
            - redis
        container_name: app
        command: ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            QUEUE_CONNECTION: redis

    db:
        image: postgres:13
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8101:5432"
        container_name: db

    redis:
        image: redis:7
        container_name: redis
        restart: always
        command: [ "redis-server", "--appendonly", "yes" ]
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    db_data:
    redis_data:

networks:
    default:
        name: global_net
        external: true
